eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        hostname: localhost
microservice:
  landtransport:
    endpoints:
      endpoint:
        uri: http://Land-transport-controller/land/landtransport
microservice:
  airtransport:
    endpoints:
      endpoint:
        uri: http://Air-transport-controller/air/airtransport
        
